/* Autogenerated v4-0-0 from https://github.com/scottprahl/iad */

void AGrid_Build(struct measure_type m, struct invert_type r);

int AGrid_Valid(struct measure_type m, struct invert_type r);

int AGrid_Fill_Guesses(double m_r, double m_t, guess_type * guesses, int max_n);
