/* Autogenerated v3-16-3 from https://github.com/scottprahl/iad */

double What_Is_B(struct AD_slab_type slab, double Tu);

void Estimate_RT(struct measure_type m, struct invert_type r, double *rt, double *tt,
    double *rd, double *rc, double *td, double *tc);

double a2acalc(double a);

double acalc2a(double acalc);

double g2gcalc(double g);

double gcalc2g(double gcalc);

double b2bcalc(double b);

double bcalc2b(double bcalc);

void Set_Debugging(unsigned long debug_level);

void Calculate_Mua_Musp(struct measure_type m, struct invert_type r, double *mus, double *musp, double *mua);

int Debug(unsigned long mask);

double sqr(double x);

void Print_Invert_Type(struct invert_type r);

void Print_Measure_Type(struct measure_type m);
