/* Autogenerated v3-16-3 from https://github.com/scottprahl/iad */

#include <math.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "nr_zbrent.h"
#include "ad_globl.h"
#include "ad_frsnl.h"
#include "ad_prime.h"
#include "iad_type.h"
#include "iad_util.h"
#include "iad_calc.h"

#define ABIT 1e-6

#define REFLECTION_SPHERE 1
#define TRANSMISSION_SPHERE 0
#define T_TRUST_FACTOR 1

#define SWAP(a,b) {double swap= (a);(a)= (b);(b)= swap;}

static int CALCULATING_GRID = 0;
static int SKIP_DISTANCE_CLAMP = 0;
static struct measure_type MM;
static struct invert_type RR;

static double scaled_l2_component(double calculated, double measured)
{
    double residual = calculated - measured;
    double scale = fabs(measured);
    if (scale < 0.01)
        scale = 0.01;
    return (residual / scale) * (residual / scale);
}

void Set_Calc_State(struct measure_type m, struct invert_type r)
{
    memcpy(&MM, &m, sizeof(struct measure_type));
    memcpy(&RR, &r, sizeof(struct invert_type));
}

void Get_Calc_State(struct measure_type *m, struct invert_type *r)
{
    memcpy(m, &MM, sizeof(struct measure_type));
    memcpy(r, &RR, sizeof(struct invert_type));
}

void RT_Flip(int flip, int n, struct AD_slab_type *slab, double *UR1, double *UT1, double *URU, double *UTU)
{
    double correct_UR1, correct_URU;
    RT(n, slab, UR1, UT1, URU, UTU);
    if (flip) {
        correct_UR1 = *UR1;
        correct_URU = *URU;
        SWAP(slab->n_top_slide, slab->n_bottom_slide)
            SWAP(slab->b_top_slide, slab->b_bottom_slide)
            RT(n, slab, UR1, UT1, URU, UTU);
        SWAP(slab->n_top_slide, slab->n_bottom_slide)
            SWAP(slab->b_top_slide, slab->b_bottom_slide)
            * UR1 = correct_UR1;
        *URU = correct_URU;
    }
}

double Gain(int sphere, struct measure_type m, double uru_sample, double uru_third)
{
    double inv_gain;

    if (sphere == REFLECTION_SPHERE) {
        if (m.baffle_r) {
            inv_gain = m.rw_r + (m.at_r / m.aw_r) * uru_third;
            inv_gain *= m.aw_r + (1 - m.at_r) * (m.ad_r * m.rd_r + m.as_r * uru_sample);
            inv_gain = 1.0 - inv_gain;
        }
        else {
            inv_gain = 1.0 - m.aw_r * m.rw_r - m.ad_r * m.rd_r - m.as_r * uru_sample - m.at_r * uru_third;
        }
    }
    else if (m.baffle_t) {
        inv_gain = m.rw_t + (m.at_t / m.aw_t) * uru_third;
        inv_gain *= m.aw_t + (1 - m.at_t) * (m.ad_t * m.rd_t + m.as_t * uru_sample);
        inv_gain = 1.0 - inv_gain;
    }
    else {
        inv_gain = 1.0 - m.aw_t * m.rw_t - m.ad_t * m.rd_t - m.as_t * uru_sample - m.at_t * uru_third;
    }
    return 1.0 / inv_gain;
}

double Gain_11(struct measure_type m, double URU, double tdiffuse)
{
    double G, GP, G11;

    G = Gain(REFLECTION_SPHERE, m, URU, 0);
    GP = Gain(TRANSMISSION_SPHERE, m, URU, 0);

    G11 = G / (1 - m.as_r * m.as_t * m.aw_r * m.aw_t * (1 - m.at_r) * (1 - m.at_t)
        * G * GP * tdiffuse * tdiffuse);

    return G11;
}

double Gain_22(struct measure_type m, double URU, double tdiffuse)
{
    double G, GP, G22;

    G = Gain(REFLECTION_SPHERE, m, URU, 0);
    GP = Gain(TRANSMISSION_SPHERE, m, URU, 0);

    G22 = GP / (1 - m.as_r * m.as_t * m.aw_r * m.aw_t * (1 - m.at_r) * (1 - m.at_t)
        * G * GP * tdiffuse * tdiffuse);

    return G22;
}

double Two_Sphere_R(struct measure_type m, double UR1, double URU, double UT1, double UTU)
{
    double x, GP;
    GP = Gain(TRANSMISSION_SPHERE, m, URU, 0);

    x = m.ad_r * (1 - m.at_r) * m.rw_r * Gain_11(m, URU, UTU);
    x *= (1 - m.f_r) * UR1 + m.rw_r * m.f_r + (1 - m.f_r) * m.as_t * (1 - m.at_t) * m.rw_t * UT1 * UTU * GP;
    return x;
}

double Two_Sphere_T(struct measure_type m, double UR1, double URU, double UT1, double UTU)
{
    double x, G;
    G = Gain(REFLECTION_SPHERE, m, URU, 0);
    x = m.ad_t * (1 - m.at_t) * m.rw_t * Gain_22(m, URU, UTU);
    x *= (1 - m.f_r) * UT1 + (1 - m.at_r) * m.rw_r * m.as_r * UTU * (m.f_r * m.rw_r + (1 - m.f_r) * UR1) * G;
    return x;
}

void Calculate_Distance_With_Corrections(double UR1, double UT1,
    double Ru, double Tu, double URU, double UTU, double *M_R, double *M_T, double *dev)
{

    double UR1_calc, UT1_calc, URU_calc, UTU_calc;

    URU_calc = URU - MM.uru_lost;
    if (!SKIP_DISTANCE_CLAMP && URU_calc < 0)
        URU_calc = 0;

    UTU_calc = UTU - MM.utu_lost;
    if (!SKIP_DISTANCE_CLAMP && UTU_calc < 0)
        UTU_calc = 0;

    UR1_calc = UR1 - (1.0 - MM.fraction_of_ru_in_mr) * Ru - MM.ur1_lost;
    if (!SKIP_DISTANCE_CLAMP && UR1_calc < 0)
        UR1_calc = 0;

    UT1_calc = UT1 - (1.0 - MM.fraction_of_tu_in_mt) * Tu - MM.ut1_lost;
    if (!SKIP_DISTANCE_CLAMP && UT1_calc < 0)
        UT1_calc = 0;

    switch (MM.num_spheres) {
    case 0:

        {
            *M_R = UR1_calc;
            *M_T = UT1_calc;
        }

        break;

    case 1:
        if (MM.method == COMPARISON) {

            {
                *M_R = UR1_calc;
                *M_T = UT1_calc;
            }

        }
        else {

            double P_std, P, P_0, G, G_0, G_std, r_first, P_ss, P_su;
            r_first = 1;

            if (MM.baffle_r)
                r_first = MM.rw_r * (1 - MM.at_r);

            UR1_calc = UR1 - Ru - MM.ur1_lost;
            if (!SKIP_DISTANCE_CLAMP && UR1_calc < 0)
                UR1_calc = 0;

            G_0 = Gain(REFLECTION_SPHERE, MM, 0.0, 0.0);
            G = Gain(REFLECTION_SPHERE, MM, URU_calc, 0.0);
            G_std = Gain(REFLECTION_SPHERE, MM, MM.rstd_r, 0.0);

            P_std = G_std * (MM.rstd_r * (1 - MM.f_r) + MM.f_r * MM.rw_r);
            P_0 = G_0 * (MM.f_r * MM.rw_r);
            P_ss = r_first * (UR1_calc * (1 - MM.f_r) + MM.f_r * MM.rw_r);
            P_su = MM.rw_r * (1 - MM.f_r) * MM.fraction_of_ru_in_mr * Ru;
            P = G * (P_ss + P_su);

            *M_R = MM.rstd_r * (P - P_0) / (P_std - P_0);

            if (Debug(DEBUG_SPHERE_GAIN) && !CALCULATING_GRID) {
                double G_none, P_none, M_none;
                G_none = Gain(REFLECTION_SPHERE, MM, URU, 0.0);
                P_none = G_none * (P_ss + P_su);
                M_none = MM.rstd_r * (P_none - P_0) / (P_std - P_0);
                fprintf(stderr, "SPHERE: REFLECTION\n");
                fprintf(stderr, "SPHERE:       baffle = %d\n", MM.baffle_r);
                fprintf(stderr, "SPHERE:       R_u collected = %5.1f%%\n", MM.fraction_of_ru_in_mr * 100);
                fprintf(stderr, "SPHERE:       hits sphere wall first = %5.1f%%\n", MM.f_r * 100);
                fprintf(stderr, "SPHERE:       UR1 = %7.3f   UR1_calc = %7.3f\n", UR1, UR1_calc);
                fprintf(stderr, "SPHERE:       URU = %7.3f   URU_calc = %7.3f\n", URU, URU_calc);
                fprintf(stderr, "SPHERE:       R_u = %7.3f\n", Ru);
                fprintf(stderr, "SPHERE:       G_0 = %7.3f        P_0 = %7.3f\n", G_0, P_0);
                fprintf(stderr, "SPHERE:         G = %7.3f          P = %7.3f\n", G, P);
                if (MM.uru_lost > 0)
                    fprintf(stderr, "SPHERE: G_no_lost = %7.3f  P_no_lost = %7.3f\n", G_none, P_none);
                fprintf(stderr, "SPHERE:     G_cal = %7.3f      P_cal = %7.3f\n", G_std, P_std);
                if (MM.uru_lost > 0)
                    fprintf(stderr, "SPHERE: M_no_lost = %7.3f\n", M_none);
                fprintf(stderr, "SPHERE:       M_R = %7.3f\n", *M_R);
            }

            {
                double r_cal, r_third, P_su, P_ss;
                double r_first = 1;

                if (MM.at_t == 0) {
                    r_cal = MM.rw_t;
                    r_third = MM.rw_t;
                }
                else if (MM.fraction_of_tu_in_mt > 0) {
                    r_cal = MM.rstd_t;
                    r_third = MM.rstd_t;
                }
                else {
                    r_cal = MM.rstd_t;
                    r_third = 0;
                }

                if (MM.baffle_t)
                    r_first = MM.rw_t * (1 - MM.at_t) + r_third * MM.at_t;

                UT1_calc = UT1 - Tu - MM.ut1_lost;
                if (!SKIP_DISTANCE_CLAMP && UT1_calc < 0)
                    UT1_calc = 0;

                G = Gain(TRANSMISSION_SPHERE, MM, URU_calc, r_third);
                G_std = Gain(TRANSMISSION_SPHERE, MM, 0, r_cal);

                P_su = r_third * Tu * MM.fraction_of_tu_in_mt;
                P_ss = r_first * UT1_calc;

                *M_T = (P_su + P_ss) * G / G_std;

                if (Debug(DEBUG_SPHERE_GAIN) && !CALCULATING_GRID) {
                    double G_none, P_none, M_none;
                    G_none = Gain(TRANSMISSION_SPHERE, MM, URU, 0.0);
                    P_none = (P_ss + P_su);
                    M_none = (P_su + P_ss) * G_none / G_std;
                    fprintf(stderr, "SPHERE: TRANSMISSION\n");
                    fprintf(stderr, "SPHERE:       baffle = %d\n", MM.baffle_t);
                    fprintf(stderr, "SPHERE:       T_u collected = %5.1f%%\n", MM.fraction_of_tu_in_mt * 100);
                    fprintf(stderr, "SPHERE:       UR1 = %7.3f   UR1_calc = %7.3f\n", UR1, UR1_calc);
                    fprintf(stderr, "SPHERE:       URU = %7.3f   URU_calc = %7.3f\n", URU, URU_calc);
                    fprintf(stderr, "SPHERE:       UT1 = %7.3f   UT1_calc = %7.3f\n", UT1, UT1_calc);
                    fprintf(stderr, "SPHERE:       T_u = %7.3f\n", Tu);
                    fprintf(stderr, "SPHERE:         G = %7.3f          P = %7.3f\n", G, P_su + P_ss);
                    if (MM.uru_lost > 0)
                        fprintf(stderr, "SPHERE: G_no_lost = %7.3f  P_no_lost = %7.3f\n", G_none, P_none);
                    fprintf(stderr, "SPHERE:     G_cal = %7.3f      P_cal = %7.3f\n", G_std, 1.0);
                    fprintf(stderr, "SPHERE:   r_third = %7.3f      r_cal = %7.3f\n", r_third, r_cal);
                    fprintf(stderr, "SPHERE:   r_first = %7.3f\n", r_first);
                    fprintf(stderr, "SPHERE:       Psu = %7.3f        Pss = %7.3f\n", P_su, P_ss);
                    if (MM.uru_lost > 0)
                        fprintf(stderr, "SPHERE: M_no_lost = %7.3f\n", M_none);
                    fprintf(stderr, "SPHERE:       M_T = %7.3f\n", *M_T);
                    fprintf(stderr, "\n");
                }
            }

        }
        break;

    case 2:

        {
            double R_0, T_0;
            R_0 = Two_Sphere_R(MM, 0, 0, 0, 0);
            T_0 = Two_Sphere_T(MM, 0, 0, 0, 0);

            *M_R = MM.rstd_r * (Two_Sphere_R(MM, UR1_calc, URU_calc, UT1_calc, UTU_calc) - R_0) /
                (Two_Sphere_R(MM, MM.rstd_r, MM.rstd_r, 0, 0) - R_0);
            *M_T = (Two_Sphere_T(MM, UR1_calc, URU_calc, UT1_calc, UTU_calc) - T_0) /
                (Two_Sphere_T(MM, 0, 0, 1, 1) - T_0);
        }

        break;

    default:
        fprintf(stderr, "Bad number of spheres = %d\n", MM.num_spheres);
        exit(EXIT_FAILURE);
    }

    if (RR.search == FIND_A || RR.search == FIND_G || RR.search == FIND_B ||
        RR.search == FIND_Bs || RR.search == FIND_Ba) {

        if (RR.metric == L2_SCALED) {
            if (MM.m_t > 0)
                *dev = scaled_l2_component(*M_T, MM.m_t);
            else
                *dev = scaled_l2_component(*M_R, MM.m_r);
        }
        else if (MM.m_t > 0) {
            if (RR.metric == RELATIVE)
                *dev = fabs(MM.m_t - *M_T) / (MM.m_t + ABIT);
            else
                *dev = fabs(MM.m_t - *M_T);
        }
        else {
            if (RR.metric == RELATIVE)
                *dev = fabs(MM.m_r - *M_R) / (MM.m_r + ABIT);
            else
                *dev = fabs(MM.m_r - *M_R);
        }

    }
    else {

        if (RR.metric == L2_SCALED) {
            *dev = scaled_l2_component(*M_T, MM.m_t);
            if (RR.default_a != 0)
                *dev += scaled_l2_component(*M_R, MM.m_r);
        }
        else if (RR.metric == RELATIVE) {
            if (MM.m_t > ABIT)
                *dev = T_TRUST_FACTOR * fabs(MM.m_t - *M_T) / (UTU_calc + ABIT);
            if (RR.default_a != 0) {
                *dev += fabs(MM.m_r - *M_R) / (URU_calc + ABIT);
            }
        }
        else {
            *dev = T_TRUST_FACTOR * fabs(MM.m_t - *M_T);
            if (RR.default_a != 0)
                *dev += fabs(MM.m_r - *M_R);
        }

    }

    if ((Debug(DEBUG_ITERATIONS) && !CALCULATING_GRID) || (Debug(DEBUG_GRID_CALC) && CALCULATING_GRID)) {
        fprintf(stderr, "%10.5f %10.4f %10.5f |", RR.slab.a, RR.slab.b, RR.slab.g);
        fprintf(stderr, " %10.5f %10.5f |", MM.m_r, *M_R);
        fprintf(stderr, " %10.5f %10.5f |", MM.m_t, *M_T);
        fprintf(stderr, "%10.3f\n", *dev);
    }

}

void Calculate_Distance(double *M_R, double *M_T, double *deviation)
{
    double Ru, Tu, ur1, ut1, uru, utu;

    if (RR.slab.b <= 1e-6)
        RR.slab.b = 1e-6;

    RT_Flip(MM.flip_sample, RR.method.quad_pts, &RR.slab, &ur1, &ut1, &uru, &utu);

    Sp_mu_RT_Flip(MM.flip_sample,
        RR.slab.n_top_slide, RR.slab.n_slab, RR.slab.n_bottom_slide,
        RR.slab.b_top_slide, RR.slab.b, RR.slab.b_bottom_slide, RR.slab.cos_angle, &Ru, &Tu);

    if ((!CALCULATING_GRID && Debug(DEBUG_ITERATIONS)) || (CALCULATING_GRID && Debug(DEBUG_GRID_CALC)))
        fprintf(stderr, "        ");

    Calculate_Distance_With_Corrections(ur1, ut1, Ru, Tu, uru, utu, M_R, M_T, deviation);
}

void abg_distance(double a, double b, double g, guess_type *guess)
{
    double m_r, m_t, distance;
    struct measure_type old_mm;
    struct invert_type old_rr;

    Get_Calc_State(&old_mm, &old_rr);

    RR.slab.a = a;
    RR.slab.b = b;
    RR.slab.g = g;

    Calculate_Distance(&m_r, &m_t, &distance);

    Set_Calc_State(old_mm, old_rr);

    guess->a = a;
    guess->b = b;
    guess->g = g;
    guess->distance = distance;
}

void abg_eval(double a, double b, double g, double *ur1, double *ut1, double *uru, double *utu)
{
    struct measure_type old_mm;
    struct invert_type old_rr;

    Get_Calc_State(&old_mm, &old_rr);

    RR.slab.a = a;
    RR.slab.b = (b < 1e-6) ? 1e-6 : b;
    RR.slab.g = g;

    RT_Flip(MM.flip_sample, RR.method.quad_pts, &RR.slab, ur1, ut1, uru, utu);

    Set_Calc_State(old_mm, old_rr);
}

double abg_stored_distance(double a, double b, double g, double ur1, double ut1, double uru, double utu)
{
    double mr, mt;
    double residual, scale, dev;
    int two_param, include_r;
    struct measure_type old_mm;
    struct invert_type old_rr;

    abg_sphere_mr_mt(a, b, g, ur1, ut1, uru, utu, &mr, &mt);

    Get_Calc_State(&old_mm, &old_rr);
    RR.slab.a = a;
    RR.slab.b = (b < 1e-6) ? 1e-6 : b;
    RR.slab.g = g;

    two_param = (RR.search == FIND_AB || RR.search == FIND_AG || RR.search == FIND_BG);
    dev = 0.0;

    if (two_param) {
        scale = fabs(MM.m_t);
        if (scale < 0.01)
            scale = 0.01;
        residual = mt - MM.m_t;
        dev = (residual / scale) * (residual / scale);

        include_r = (RR.default_a == UNINITIALIZED) || (fabs(RR.default_a) > 1e-10);
        if (include_r) {
            scale = fabs(MM.m_r);
            if (scale < 0.01)
                scale = 0.01;
            residual = mr - MM.m_r;
            dev += (residual / scale) * (residual / scale);
        }
    }
    else {
        if (MM.m_r > 0) {
            scale = fabs(MM.m_r);
            if (scale < 0.01)
                scale = 0.01;
            residual = mr - MM.m_r;
            dev += (residual / scale) * (residual / scale);
        }
        if (MM.m_t > 0) {
            scale = fabs(MM.m_t);
            if (scale < 0.01)
                scale = 0.01;
            residual = mt - MM.m_t;
            dev += (residual / scale) * (residual / scale);
        }
    }

    Set_Calc_State(old_mm, old_rr);

    return dev;
}

void abg_sphere_mr_mt(double a, double b, double g,
    double ur1, double ut1, double uru, double utu, double *mr, double *mt)
{
    double Ru, Tu, dev;
    struct measure_type old_mm;
    struct invert_type old_rr;

    Get_Calc_State(&old_mm, &old_rr);

    RR.slab.a = a;
    RR.slab.b = (b < 1e-6) ? 1e-6 : b;
    RR.slab.g = g;

    MM.ur1_lost = 0.0;
    MM.ut1_lost = 0.0;
    MM.uru_lost = 0.0;
    MM.utu_lost = 0.0;

    Sp_mu_RT_Flip(MM.flip_sample,
        RR.slab.n_top_slide, RR.slab.n_slab, RR.slab.n_bottom_slide,
        RR.slab.b_top_slide, RR.slab.b, RR.slab.b_bottom_slide, RR.slab.cos_angle, &Ru, &Tu);

    CALCULATING_GRID = 1;
    Calculate_Distance_With_Corrections(ur1, ut1, Ru, Tu, uru, utu, mr, mt, &dev);
    CALCULATING_GRID = 0;

    Set_Calc_State(old_mm, old_rr);
}

double Find_AG_fn(double x[])
{
    double m_r, m_t, deviation;
    RR.slab.a = x[1];
    RR.slab.g = x[2];
    Calculate_Distance(&m_r, &m_t, &deviation);
    return deviation;
}

double Find_AB_fn(double x[])
{
    double m_r, m_t, deviation;
    RR.slab.a = x[1];
    RR.slab.b = x[2];
    Calculate_Distance(&m_r, &m_t, &deviation);
    return deviation;
}

double Find_Ba_fn(double x)
{
    double m_r, m_t, deviation, ba, bs;

    bs = RR.slab.b;
    ba = bcalc2b(x);
    RR.slab.b = ba + bs;
    RR.slab.a = bs / (ba + bs);

    Calculate_Distance(&m_r, &m_t, &deviation);

    RR.slab.b = bs;
    return deviation;
}

double Find_Bs_fn(double x)
{
    double m_r, m_t, deviation, ba, bs;

    ba = RR.slab.b;
    bs = bcalc2b(x);
    RR.slab.b = ba + bs;
    RR.slab.a = bs / (ba + bs);

    Calculate_Distance(&m_r, &m_t, &deviation);

    RR.slab.b = ba;
    return deviation;
}

double Find_A_fn(double x)
{
    double m_r, m_t, deviation;
    RR.slab.a = acalc2a(x);
    Calculate_Distance(&m_r, &m_t, &deviation);
    return deviation;
}

double Find_B_fn(double x)
{
    double m_r, m_t, deviation;
    RR.slab.b = bcalc2b(x);
    Calculate_Distance(&m_r, &m_t, &deviation);
    return deviation;
}

double Find_G_fn(double x)
{
    double m_r, m_t, deviation;
    RR.slab.g = gcalc2g(x);
    Calculate_Distance(&m_r, &m_t, &deviation);
    return deviation;
}

double Find_BG_fn(double x[])
{
    double m_r, m_t, deviation;
    RR.slab.b = x[1];
    RR.slab.g = x[2];
    RR.slab.a = RR.default_a;
    Calculate_Distance(&m_r, &m_t, &deviation);
    return deviation;
}

double Find_BaG_fn(double x[])
{
    double m_r, m_t, deviation;

    RR.slab.b = bcalc2b(x[1]) + RR.default_bs;
    if (RR.slab.b <= 0)
        RR.slab.a = 0;
    else
        RR.slab.a = RR.default_bs / RR.slab.b;

    RR.slab.g = gcalc2g(x[2]);

    Calculate_Distance(&m_r, &m_t, &deviation);
    return deviation;
}

double Find_BsG_fn(double x[])
{
    double m_r, m_t, deviation;

    RR.slab.b = bcalc2b(x[1]) + RR.default_ba;
    if (RR.slab.b <= 0)
        RR.slab.a = 0;
    else
        RR.slab.a = 1.0 - RR.default_ba / RR.slab.b;

    RR.slab.g = gcalc2g(x[2]);
    Calculate_Distance(&m_r, &m_t, &deviation);
    return deviation;
}

double maxloss(double f)
{
    struct measure_type m_old;
    struct invert_type r_old;
    double m_r, m_t, deviation;

    Get_Calc_State(&m_old, &r_old);

    RR.slab.a = 1.0;
    MM.ur1_lost *= f;
    MM.ut1_lost *= f;

    Calculate_Distance(&m_r, &m_t, &deviation);

    Set_Calc_State(m_old, r_old);
    deviation = ((MM.m_r + MM.m_t) - (m_r + m_t));

    return deviation;
}

void Max_Light_Loss(struct measure_type m, struct invert_type r, double *ur1_loss, double *ut1_loss)
{
    struct measure_type m_old;
    struct invert_type r_old;

    *ur1_loss = m.ur1_lost;
    *ut1_loss = m.ut1_lost;

    if (Debug(DEBUG_LOST_LIGHT))
        fprintf(stderr, "\nlost before ur1=%7.5f, ut1=%7.5f\n", *ur1_loss, *ut1_loss);

    Get_Calc_State(&m_old, &r_old);

    Set_Calc_State(m, r);

    if (maxloss(1.0) * maxloss(0.0) < 0) {
        double frac;
        frac = zbrent(maxloss, 0.00, 1.0, 0.001);

        *ur1_loss = m.ur1_lost * frac;
        *ut1_loss = m.ut1_lost * frac;
    }

    Set_Calc_State(m_old, r_old);
    if (Debug(DEBUG_LOST_LIGHT))
        fprintf(stderr, "lost after  ur1=%7.5f, ut1=%7.5f\n", *ur1_loss, *ut1_loss);
}
