/* Autogenerated v3-16-3 from https://github.com/scottprahl/iad */

void MC_Set_Seed(unsigned long seed);

void MC_Lost(struct measure_type m, struct invert_type r, long n_photons,
    double *ur1, double *ut1, double *uru, double *utu,
    double *ur1_lost, double *ut1_lost, double *uru_lost, double *utu_lost);

void MC_RT(struct AD_slab_type s, long n_photons, double t_sample,
    double t_slide, double *UR1, double *UT1, double *URU, double *UTU);

void MC_Radial(long photons, double a, double b, double g, double n_sample,
    double n_slide, double cos_cone_angle, double cos_incidence,
    double t_sample, double t_slide, double b_slide,
    double dr_port, double dt_port, double d_beam, double *r_total, double *t_total, double *r_lost, double *t_lost);

void MC_Print_RT_Arrays(int status);

void MC_Lost_With_Stderr(struct measure_type m, struct invert_type r,
    long n_photons, int n_repeats,
    double *ur1, double *ut1, double *uru, double *utu,
    double *mean_ur1_lost, double *mean_ut1_lost,
    double *mean_uru_lost, double *mean_utu_lost,
    double *se_ur1_lost, double *se_ut1_lost, double *se_uru_lost, double *se_utu_lost);
