/* Autogenerated v3-16-3 from https://github.com/scottprahl/iad */

The version number obtained from <.. / Makefile >
    The date is the last change to < version.h > */char *Version = "3-16-3 (19 Jun 2025)";
char *VersionShort = "3-16-3";
