name: Make

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Download GitHub repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download CWEB source and extract source
      run: |
        mkdir cweb
        wget https://github.com/ascherer/cweb/releases/download/cweb-4.11/cweb-4.11.tar.gz
        tar xvfz cweb-4.11.tar.gz -C cweb
    
    - name: Compile and Install CWEB
      run: |
        cd cweb
        make
        cp ctangle /usr/local/bin/ctangle
        chmod 755 /usr/local/bin/ctangle
        cd ..
    
    - name: Run short test (no automated verification)
      run: |
        make
        make veryshorttest

  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Download GitHub repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install required doc tools
      run:  |
        sudo apt install -y texlive texlive-extra-utils texlive-latex-extra qpdf

    - name: Build docs
      run: make doc

    - name: Upload generated docs artefacts
      uses: actions/upload-artifact@v3
      with:
        name: generated-docs
        path: |
          doc/ad_src.pdf
          doc/iad_src.pdf
          doc/manual.pdf

